- mmdnn/conversion/examples/caffe/extract_model.py
add caffe example to extract model
> add caffe example to extract model

- mmdnn/conversion/caffe/graph.py
The current code version uses the filename `deploy.prototxt` for a temporary operation, and potentially deletes a user-created file of the same name.
This pull request fixes this problem by using a temporary filename.
> Do not overwrite existing 'deploy.prototxt' when converting from Caffe model

- mmdnn/conversion/caffe/mapper.py
- mmdnn/conversion/examples/tensorflow/imagenet_test.py
> Caffe resnet152 to tf conversion passed.

- mmdnn/conversion/mxnet/mxnet_emitter.py
add support to ReLU6 with replacement emit_Relu function.
> add support to ReLU6 with replacement emit_Relu function

- mmdnn/conversion/tensorflow/tensorflow_parser.py
check existence in checkpoint data while converting variables in batchnorm layers
> check existence in checkpoint data

- mmdnn/conversion/mxnet/mxnet_emitter.py
map relu6 to relu for mxnet symbol definition
> map relu6 to relu for mxnet

- mmdnn/conversion/coreml/coreml_emitter.py
Test relu6 reshape embedding depth-wise convolution
> Test relu6 reshape embedding depth-wise convolution

- mmdnn/conversion/caffe/caffe_emitter.py
> Caffe emitter

- mmdnn/conversion/mxnet/mxnet_emitter.py
fix bug in mxnet_emitter.py on create destination weight file
> fix bugs in mxnet_emitter.py on create destination weight file

- mmdnn/conversion/_script/extractModel.py
- mmdnn/conversion/examples/imagenet_test.py
- mmdnn/conversion/examples/keras/extractor.py
- test/conversion/keras2cntk.py
test 9 models from keras to cntk
> keras to cntk test

- tests/test_conversion_imagenet.py
> keras2keras

- tests/test_conversion_imagenet.py
> to pytorch test

- mmdnn/conversion/examples/cntk/extractor.py
- mmdnn/conversion/examples/imagenet_test.py
- tests/test_conversion_imagenet.py
cntk parser, extractor and  MXNetEmit
>  cntk parser, extractor and  MXNetEmit

- README.md
I started from a stock conda environment and needed to install requests, tensorflow, and keras in order to get the visualization sample to work.
> Minor update to visualization example

- mmdnn/conversion/keras/keras2_parser.py
> keras paser Embedding GRU

- mmdnn/conversion/onnx/shape_inference.py
1. add Flatten operation,
2. add LeNet-5 shape inference test, LeNet-5 includes Conv, pool, FC, Flatten operation.
> add LeNet-5 as shape inference test, and add Flatten operation

- mmdnn/conversion/tensorflow/tensorflow_emitter.py
Support of PReLU activation function in tensorflow emitter.
Partial solution for issue #89
> PReLU support in tensorflow emitter

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
tensorflow frozen protobuf parser
> tensorflow frozen protobuf parser

- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
tensorflow frozenparser inception_v1
> tensorflow frozenparser inception_v1

- mmdnn/conversion/caffe/caffe_emitter.py
- mmdnn/conversion/examples/tensorflow/extractor.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
- tests/test_conversion_imagenet.py
> tensorflow frozenpb test

- mmdnn/conversion/coreml/coreml_emitter.py
Note: I haven't tested yet if this gives the correct output, but I am assuming it should.
Also, you should consider adding .DS_Store to the .gitignore, since these files are very prevalant when working on a mac.
> Added PRelu to CoreML emitter.

- mmdnn/conversion/mxnet/mxnet_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
- tests/test_conversion_imagenet.py
> frozen tensorflow test fix

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/examples/tensorflow/extractor.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
- tests/test_conversion_imagenet.py
frozen parser subgraph and test
> frozen parser subgraph and test

- tests/test_conversion_imagenet.py
> CoremlEmit test

- mmdnn/conversion/examples/tensorflow/extractor.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
- tests/test_conversion_imagenet.py
TF frozen parser mobilenet test
> TF frozen parser mobilenet test

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
- mmdnn/conversion/torch/torch_parser.py
TF frozen paser fix input_shape & new network style ssd
> TF frozen paser fix input_shape & new network style ssd

- mmdnn/conversion/coreml/coreml_emitter.py
- tests/test_conversion_imagenet.py
> coreml emit test & LRN

- tests/test_conversion_imagenet.py
>  darknet unittest

- mmdnn/conversion/darknet/darknet_graph.py
- mmdnn/conversion/darknet/prototxt.py
> darknet py3 fix

- mmdnn/conversion/onnx/README.md
- mmdnn/conversion/onnx/onnx_emitter.py
> onnx emitter supports channel last IR now

- mmdnn/conversion/coreml/coreml_emitter.py
> xception test passed

- tests/test_conversion_imagenet.py
Keras DenseNet to ONNX test passed.
> Add ONNX emitter test

- README.md
- mmdnn/conversion/mxnet/mxnet_parser.py
- mmdnn/conversion/tensorflow/tensorflow_emitter.py
- left strip the '_' of node name 
- add the flatten layer before fc layer if not
> modifed to issue #85

- mmdnn/conversion/coreml/coreml_parser.py
- mmdnn/conversion/tensorflow/tensorflow_emitter.py
- tests/test_conversion_imagenet.py
add leaky_relu in tensorflow and set variable dtype in coreml
> coreml to tensorflow passed

- mmdnn/conversion/coreml/coreml_parser.py
- mmdnn/conversion/mxnet/mxnet_emitter.py
- tests/test_conversion_imagenet.py
The tinyyolo example fails because of the symmetric padding in mxnet.
> coreml to mxnet tests passed

- mmdnn/conversion/onnx/onnx_emitter.py
- tests/test_conversion_imagenet.py
tested on VGG16, VGG19, InceptionV3, ResNet50 and DenseNet.
> Keras to ONNX tests passed

- mmdnn/conversion/onnx/onnx_emitter.py
- tests/test_conversion_imagenet.py
tested on vgg19, imagenet1k-inception-bn, imagenet1k-resnet-18, imagenet1k-resnet-152, squeezenet_v1.1, imagenet1k-resnext-101-64x4d and imagenet1k-resnext-50.
> MXNet to ONNX tests passed

- mmdnn/conversion/examples/imagenet_test.py
- mmdnn/conversion/examples/tensorflow/extractor.py
- mmdnn/conversion/examples/tensorflow/models/mobilenet/conv_blocks.py
- mmdnn/conversion/examples/tensorflow/models/mobilenet/mobilenet.py
- mmdnn/conversion/examples/tensorflow/models/mobilenet/mobilenet_v2.py
- tests/test_conversion_imagenet.py
> mobilenet v2 passed

- mmdnn/conversion/onnx/onnx_emitter.py
- tests/test_conversion_imagenet.py
tested on `alexnet`, `inception_v1`, `inception_v4`, `resnet152`, `squeezenet`, `vgg19` and `xception`.
> Caffe to ONNX tests passed

- mmdnn/conversion/coreml/README.md
- mmdnn/conversion/coreml/coreml_parser.py
- mmdnn/conversion/examples/cntk/extract_model.py
- mmdnn/conversion/pytorch/pytorch_emitter.py
- tests/test_conversion_imagenet.py
> coreml to pytorch conversion passed

- mmdnn/conversion/onnx/onnx_emitter.py
- tests/test_conversion_imagenet.py
tested on `mobilenet_v1_1.0`, `mobilenet_v2_1.0_224` and `nasnet-a_large`.
TensorFlow_frozen tested on `mobilenet_v1_1.0`.
> TensorFlow (and frozen) to ONNX tests passed

- mmdnn/conversion/caffe/README.md
- mmdnn/conversion/cntk/README.md
- mmdnn/conversion/keras/README.md
- mmdnn/conversion/mxnet/README.md
- mmdnn/conversion/tensorflow/README.md
> Update convert table with onnx results

- mmdnn/conversion/_script/dump_code.py
Fix issue #205 [Unable to generate PyTorch model from code snippet file and weight file]
> Fix issue #205

- mmdnn/conversion/examples/imagenet_test.py
> change to PIL

- mmdnn/conversion/examples/imagenet_test.py
- mmdnn/visualization/index.html
> Float and Double problem

- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
> Add reducemean layer

- mmdnn/conversion/common/DataStructure/graph.py
- mmdnn/conversion/pytorch/pytorch_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
tensorflow frozenpb parser for ssd and fastrcnn
>  tensorflow frozenpb parser for ssd and fastrcnn

- mmdnn/conversion/coreml/coreml_emitter.py
- mmdnn/conversion/mxnet/mxnet_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
- tests/test_conversion_imagenet.py
> tensorflow resnet_v2

- mmdnn/conversion/mxnet/mxnet_emitter.py
> fix tf-mxnet bug

- mmdnn/conversion/tensorflow/tensorflow_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
change for the facenet conversion
> change for the facenet conversion

- mmdnn/conversion/caffe/mapper.py
- mmdnn/conversion/onnx/onnx_emitter.py
Hey,
There is a paper for face detection MTCNN,
It has inside 3 caffe models.
I am trying to convert them to onnx format.
This is one of the issues i have discovered.
> Added PRelu emitter

- mmdnn/conversion/caffe/caffe_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
Mul Abs Sub and Squeeze tf to caffe
>  Mul Abs Sub and Squeeze tf to caffe

- mmdnn/conversion/caffe/caffe_emitter.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
identity tf parser and squeeze caffe_emitter
> identity tf parser and squeeze caffe_emitter

- mmdnn/conversion/paddle/__init__.py
- mmdnn/conversion/paddle/paddle_graph.py
- mmdnn/conversion/pytorch/pytorch_graph.py
- mmdnn/conversion/pytorch/pytorch_parser.py
> paddle graph and pytorch graph fixed

- mmdnn/conversion/keras/keras2_parser.py
- mmdnn/conversion/tensorflow/tensorflow_emitter.py
> try to help ##236

- mmdnn/conversion/_script/convertToIR.py
> Inputshape issue of #247

- mmdnn/conversion/_script/convertToIR.py
> inputshape generalization

- mmdnn/conversion/common/DataStructure/parser.py
- mmdnn/conversion/paddle/paddle_parser.py
> paddlepaddle parser

- mmdnn/conversion/caffe/graph.py
- mmdnn/conversion/keras/keras2_parser.py
keras parser and  caffe transformer for issue 259 and 244
>  keras parser and  caffe transformer for issue 259 and 244

- mmdnn/conversion/pytorch/pytorch_parser.py
> fixes #272

- mmdnn/conversion/mxnet/mxnet_parser.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
- tests/test_conversion_imagenet.py
mxnet parser fix pooling padding and  tf parser fix and test
> mxnet parser fix pooling padding and  tf parser fix and test

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/pytorch/pytorch_graph.py
- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
pytorch graph shape fix and  fix bug
> pytorch graph shape fix and  fix bug

- mmdnn/conversion/pytorch/pytorch_parser.py
add `tanh` implement.
(And sorry for the last commit, it directly commits to the master branch. Plz double-check it.)
> pytorch tanh activation

- mmdnn/conversion/caffe/caffe_emitter.py
> add caffe `tanh`

- mmdnn/conversion/caffe/caffe_emitter.py
- mmdnn/conversion/caffe/graph.py
Add emit_ResizeBilinear function.
details in #277.
> support for tensorflow operator ResizeBilinear in caffe.

- setup.py
>  setup fix #305

- mmdnn/conversion/mxnet/mxnet_graph.py
mxnet get_attr default https://github.com/Microsoft/MMdnn/issues/307
> mxnet get_attr default https://github.com/Microsoft/MMdnn/issues/307

- mmdnn/conversion/_script/convertToIR.py
> pytorch parser args

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/keras/keras2_emitter.py
- mmdnn/conversion/keras/keras2_parser.py
keras api update relu6 and DepthwiseConv2D & caffe inputshape fix #340
>  keras api update relu6 and DepthwiseConv2D & caffe inputshape fix #340

- mmdnn/conversion/cntk/cntk_parser.py
- mmdnn/conversion/keras/keras2_emitter.py
fix https://github.com/Microsoft/MMdnn/issues/349 cntk parser slice
> fix https://github.com/Microsoft/MMdnn/issues/349 cntk parser slice

- mmdnn/conversion/mxnet/mxnet_emitter.py
Fixes #359 
Ran `test_conversion_imagenet.py` test script.
> Fix bug in MXNet emitter when input variable name differs from input layer name #359

- mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
Use distutils.version to compare version
> Fix tensorflow version check

- mmdnn/conversion/caffe/caffe_emitter.py
fix caffe_emitter constant layer to help #366
>  fix caffe_emitter constant layer to help #366

- mmdnn/conversion/caffe/mapper.py
caffe inner product output_shape
> caffe inner product output_shape

- mmdnn/conversion/mxnet/mxnet_parser.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
get_bias fix to help https://github.com/Microsoft/MMdnn/issues/398
> get_bias fix to help https://github.com/Microsoft/MMdnn/issues/398

- mmdnn/conversion/caffe/caffe_emitter.py
- mmdnn/conversion/cntk/README.md
- mmdnn/conversion/keras/keras2_parser.py
- mmdnn/conversion/mxnet/mxnet_parser.py
- mmdnn/conversion/tensorflow/tensorflow_parser.py
caffe fix symmetric padding and keras parser
>  caffe fix symmetric padding and keras parser #404

- mmdnn/conversion/mxnet/mxnet_parser.py
> Convert pad from MxNet

- README.md
- setup.py
Added the PyPi project version badge to readme.
Updated setup.py to use markdown for long description.
> Add PyPi badge, fix setup

- mmdnn/conversion/caffe/mapper.py
> Update get_handler func for None Type Exceptions

- mmdnn/visualization/README.md
- mmdnn/visualization/app.js
Thank you for open sourcing this useful tool.
In this PR, I just made some minor fix.  And I am hoping to contribute more to this project in the future.
> fix minor documentation error and enhance with a readme file

- mmdnn/conversion/onnx/onnx_parser.py
> Remove unimplemented method 'rename_Conv' in onnx_parser

- mmdnn/conversion/pytorch/pytorch_parser.py
> Add support for Sigmoid and Mul ops in PytorchParser

- mmdnn/conversion/keras/keras2_emitter.py
1. Multiplication sign `*`  replaced with `layers.Multiply`
2. Group convolution upgraded to be able to change number of filters (input filters != output filters) as usual `Conv` layers.
Modification have been checked converting pytorch [senet models](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/senet.py) (with replacement of GlobalAvgPool2d -> AvgPool2d). 
Converted models can be found [here](https://github.com/qubvel/classification_models).
> Fix mul and group convolution

- mmdnn/conversion/tensorflow/tensorflow_parser.py
Hi. I made a small change in method `_load_weights` in `tensorflow_parser.py` to parse variables trained with` tf.train.exponential_moving_average`. May this can help someone.
> add code to support tensorflow exponential moving avrage

- mmdnn/conversion/examples/tensorflow/vis_meta.py
1. Add explicit argument names for checkpoint meta file and log directory.
2. Support passing extra TensorBoard arguments.
> Improve mmvismeta.

- mmdnn/conversion/caffe/mapper.py
- mmdnn/conversion/cntk/cntk_emitter.py
- mmdnn/conversion/examples/caffe/extractor.py
- mmdnn/conversion/examples/tensorflow/extractor.py
- tests/conversion_imagenet.py
- tests/test_caffe.py
- tests/test_caffe_2.py
> Temporarily disable some test models since MMdnn server has been shut down.

- mmdnn/conversion/_script/convertToIR.py
- mmdnn/conversion/keras/keras2_emitter.py
- mmdnn/conversion/pytorch/pytorch_emitter.py
- mmdnn/conversion/pytorch/pytorch_graph.py
- mmdnn/conversion/pytorch/pytorch_parser.py
- tests/conversion_imagenet.py
Add support for torch1.5.1 and reserve support for torch0.4.0
> Update support for pytorch1.5.1

- mmdnn/conversion/pytorch/pytorch_graph.py
- mmdnn/conversion/pytorch/pytorch_parser.py
use torch.onnx provided `_trace` function(include optimization)
> change trace function for pytorch 1.5

- mmdnn/conversion/pytorch/pytorch_graph.py
- mmdnn/conversion/pytorch/pytorch_parser.py
blueprint from pull request #870
> Pytorch1.5 update extract method
