microsoft/MMdnn

mmdnn/conversion/caffe/graph.py, mmdnn/conversion/caffe/mapper.py, mmdnn/conversion/caffe/shape.py, mmdnn/conversion/caffe/transformer.py, mmdnn/conversion/keras/keras2_emitter.py
I was looking to convert a [Caffe trained colorization network](http://richzhang.github.io/colorization/) to Keras, and a few things were missing, so I added them. I didn't succeed fully :(, so whether this all works or not is not entirely certain. It is possible that some filters need flipping or something, I am unable to test this at this moment (don't have Caffe configured on this machine).
Changes:
* **Support deconvolutions/transposed convolutions**, both in Caffe input and Keras output. 
* **Dilation factors in any type of convolution**, both in Caffe input and Keras output. 
* **Ignore silence layers in Caffe graphs**
* **Minor fix:** BatchNorm weights of shape `(1,1,1,64)`or similar, are now reshaped to `(64,)` to prevent broadcasting issues.
* **Fix typo:** *paramters -> …
=> Caffe/Keras support dilation and deconvolutions + other minor fixes

mmdnn/conversion/examples/imagenet_test.py
Added the missing "__ed__".
* https://docs.python.org/3/library/exceptions.html#NotImplementedError
Caught by flake8
=> NotImplementError() --> NotImplementedError()

mmdnn/conversion/mxnet/mxnet_parser.py
There are no full support for correct 'attrs' options reading in MXNet parser.
I use already implemented '_get_layer_attr' function in all 'rename' functions.
=> MXNet parser 'attrs' corrections

mmdnn/conversion/mxnet/mxnet_parser.py
It is prelu support  for MXNet parser
=> Mxnet parser prelu support

mmdnn/conversion/caffe/caffe_emitter.py, mmdnn/conversion/coreml/coreml_parser.py, mmdnn/conversion/mxnet/mxnet_emitter.py, tests/test_conversion_imagenet.py
tiny-yolo still crack because the padding in caffe is symmetric like mxnet.
=> coreml to caffe tests passed

mmdnn/conversion/onnx/onnx_emitter.py
The current ONNX emitter aims to ONNX opset version 6.
=> Set ONNX model opset to version 6

mmdnn/conversion/keras/README.md, mmdnn/conversion/pytorch/README.md
pytorch seems that it does not need to add the `dstnodename`, isn't it? 🍡  plz double check for me.
=> readme stuff

mmdnn/conversion/pytorch/README.md, mmdnn/conversion/pytorch/pytorch_emitter.py
`emit_mul` is element-wise multiply while `emit_matmul` is matrix multiply.
=> Add pytorch emit_matmul

mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
save weights of tf.multiply operation when convert tf model to IR
details in [#303](https://github.com/Microsoft/MMdnn/issues/303)
=> Add codes for saving weights in rename_Mul() function

mmdnn/conversion/caffe/caffe_emitter.py
Replaced the previously no-op emit_Flatten in caffe_emitter with a flatten op and replaced the flatten op in Reshape with a reshape op and added support for asymmetric kernels for pooling.
=> Fixed flatten, reshape, and pooling in caffe emitter

tests/gen_test.py
__printf__ is an _undefined name_ in this context which has the potential to raise NameError at runtime.
[flake8](http://flake8.pycqa.org) testing of https://github.com/microsoft/MMdnn on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./mmdnn/conversion/torch/torch_graph.py:18:15: F821 undefined name 'PyTorchGraphNode'
super(PyTorchGraphNode, self).__init__(layer)
^
./mmdnn/conversion/examples/paddle/extract_model.py:80:63: F821 undefined name 'architecture'
fn = download_file(MODEL_URL[args.network], local_fname = architecture + '.tar.gz', directory=args.output_dir)
^
./mmdnn/conversion/examples/paddle/extract_model.py:96:20: F821 undefined name 'architecture'
if 'resnet' in architecture:
^ …
```
=> Undefined name: printf() --> print()

mmdnn/conversion/caffe/graph.py, mmdnn/conversion/caffe/transformer.py
The caffe converter does not preserve node order when converting batchnorm followed by scale layers. Take the following (very simple) network as an example:
```
name: "DemoNet"
layer {
name: "data"
type: "Input"
top: "data"
input_param: {
shape: {
dim: 1
dim: 3
dim: 224
dim: 224
}
}
}
layer {
name: "conv1"
type: "Convolution"
bottom: "data"
top: "conv1"
convolution_param {
num_output: 64
bias_term: false
pad: 3
kernel_size: 7
stride: 2
}
}
layer {
name: "conv1/bn"
type: "BatchNorm"
bottom: "conv1"
top: "conv1/bn"
batch_norm_param {
use_global_stats: true
}
}
layer {
name: "conv1/bn/scale"
type: "Scale"
bottom: "conv1/bn"
top: "conv1/bn/scale"
scale_param {
bias_term: true
}
}
layer {
name: "concat2"
bottom: "conv1/bn/scale"
bottom: "conv1"
top: "concat2"
type: "Concat"
concat_param { …
```
=> preserve order when converting batchnorm+scale layers

mmdnn/conversion/tensorflow/saver.py
solve the problem[https://github.com/microsoft/MMdnn/issues/759](url)
=> Enables multiple outputs for conversion to tensorflow

mmdnn/conversion/tensorflow/tensorflow_frozenparser.py
This change provides more clear diagnostics messages if mmdnn can't convert tensorflow frozen model
=> add None comparison to tensorflow_frozenparser

mmdnn/conversion/caffe/caffe_emitter.py, mmdnn/conversion/caffe/graph.py, mmdnn/conversion/caffe/mapper.py, mmdnn/conversion/caffe/network.py, mmdnn/conversion/caffe/shape.py, mmdnn/conversion/caffe/transformer.py, mmdnn/conversion/common/IR/ops.pbtxt, mmdnn/conversion/pytorch/pytorch_emitter.py
This pull requests enables support for unpooling layer and pooling layer with indexes from caffe with export to pytorch.
Corresponding issue #740 
Signed-off-by: Sebastien ESKENAZI <s.eskenaz@pixelz.com>
=> Add support for unpooling import from caffe and export to pytorch

README.md
Other Microsoft projects—e.g., [nni](https://github.com/microsoft/nni/blob/5f5f86c/README.md#license)—are much clearer when it comes to license, I had to scroll to the top of the page to see MIT (from GitHub not in the README).
=> [README.md] Clarify license

.gitignore, mmdnn/conversion/tensorflow/tensorflow_frozenparser.py, mmdnn/conversion/tensorflow/tensorflow_parser.py
Fix issue https://github.com/microsoft/MMdnn/issues/792
1. TensorFlow rename_DepthwiseConv2dNative() forgets to handle the bias.
2. Ignore macOS .DS_Store files.
=> Fix issue 792

mmdnn/conversion/keras/keras2_emitter.py
Fix issue https://github.com/microsoft/MMdnn/issues/847 .
=> Use keras.backends.image_data_format() since Keras >= 2.2.5 does not provide image_data_format() any more.

mmdnn/conversion/caffe/caffe_emitter.py, mmdnn/conversion/cntk/README.md, mmdnn/conversion/cntk/cntk_emitter.py, mmdnn/conversion/onnx/onnx_emitter.py, mmdnn/conversion/pytorch/pytorch_emitter.py, mmdnn/conversion/tensorflow/tensorflow_emitter.py
This PR fixes an issue in all converter generators using ``KitModel``+``__weights_dict`` architecture. See issues #668 and #631. 
The error is due to the original code erroneously using a double-underscore name at global and class scope. [At class scope, double-underscore names are subject to name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables); this leads the variable at global and class scope to *not* be equivalent.
=> Fix name mangling in KitModel

mmdnn/conversion/mxnet/mxnet_parser.py, mmdnn/conversion/tensorflow/tensorflow_emitter.py
Hello
This pull requests adds the UpSampling operator to the mxnet parser, as well as the option to chose between "bilinear" and "nearest" when emitting the UpSampling2D operator to tensorflow
The mxnet operator is necessary to convert [insightface's Retinaface](RetinaFace) from mxnet to tf
=> Add support for mxnet UpSampling parser
